import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from typing import Optional
from datetime import datetime
from config import Config
from models import Order, EmailRequest

class EmailService:
    def __init__(self, config: Config):
        self.config = config
    
    def send_order_email(self, order: Order, processing_notes: str, attachment_path: Optional[str] = None) -> bool:
        """
        Send order details to the printer/shipper via email
        """
        subject = f"New T-Shirt Order: {order.name}"
        
        # Create email body
        body = self._create_email_body(order, processing_notes)
        
        # Create email request
        email_request = EmailRequest(
            to_email=self.config.PRINTER_EMAIL,
            subject=subject,
            body=body,
            attachment_path=attachment_path
        )
        
        return self.send_email(email_request)
    
    def _create_email_body(self, order: Order, processing_notes: str) -> str:
        """
        Create formatted email body with order details
        """
        body = f"""
NEW T-SHIRT ORDER RECEIVED

Order Details:
==============
Order Number: {order.name}
Customer Email: {order.email}
Order Date: {order.created_at.strftime('%Y-%m-%d %H:%M:%S')}
Total Amount: {order.currency_code} {order.total_price}

Items Ordered:
=============
"""
        
        for item in order.line_items:
            body += f"• {item.title} (Quantity: {item.quantity}) - {order.currency_code} {item.price} each\n"
        
        body += f"""

Shipping Address:
================
"""
        
        if order.shipping_address:
            addr = order.shipping_address
            body += f"{addr.get('firstName', '')} {addr.get('lastName', '')}\n"
            body += f"{addr.get('address1', '')}\n"
            if addr.get('address2'):
                body += f"{addr.get('address2')}\n"
            body += f"{addr.get('city', '')}, {addr.get('province', '')} {addr.get('zip', '')}\n"
            body += f"{addr.get('country', '')}\n"
            if addr.get('phone'):
                body += f"Phone: {addr.get('phone')}\n"
        else:
            body += "No shipping address provided\n"
        
        body += f"""

Processing Notes:
================
{processing_notes}

Please process this order and send confirmation to the customer at {order.email}.

This email was automatically generated by the CheeseShirts API.
Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        
        return body
    
    def send_email(self, email_request: EmailRequest) -> bool:
        """
        Send email with optional attachment
        """
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.config.EMAIL_USERNAME
            msg['To'] = email_request.to_email
            msg['Subject'] = email_request.subject
            
            # Add body
            msg.attach(MIMEText(email_request.body, 'plain'))
            
            # Add attachment if provided
            if email_request.attachment_path and os.path.exists(email_request.attachment_path):
                with open(email_request.attachment_path, "rb") as attachment:
                    part = MIMEBase('application', 'octet-stream')
                    part.set_payload(attachment.read())
                
                encoders.encode_base64(part)
                
                # Get filename from path
                filename = os.path.basename(email_request.attachment_path)
                part.add_header(
                    'Content-Disposition',
                    f'attachment; filename= {filename}'
                )
                
                msg.attach(part)
            
            # Connect to server and send email
            server = smtplib.SMTP(self.config.SMTP_SERVER, self.config.SMTP_PORT)
            server.starttls()
            server.login(self.config.EMAIL_USERNAME, self.config.EMAIL_PASSWORD)
            
            text = msg.as_string()
            server.sendmail(self.config.EMAIL_USERNAME, email_request.to_email, text)
            server.quit()
            
            return True
            
        except Exception as e:
            print(f"Failed to send email: {str(e)}")
            return False
    
    def send_test_email(self, to_email: str) -> bool:
        """
        Send a test email to verify email configuration
        """
        test_request = EmailRequest(
            to_email=to_email,
            subject="CheeseShirts API - Test Email",
            body="This is a test email from the CheeseShirts API. If you receive this, the email configuration is working correctly!"
        )
        
        return self.send_email(test_request)
